CREATE DATABASE SEMINAR4
GO
USE SEMINAR4
GO


SELECT * FROM MASINA


CREATE TABLE MASINA
(
ID INT PRIMARY KEY IDENTITY ,
MODEL VARCHAR(50),
COMBUSTIBIL VARCHAR(50),
CULOARE VARCHAR(50),
KM BIGINT,
AN_FABRICATIE INT,
)

INSERT INTO MASINA (MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE) VALUES ('Hyundai' , 'Benzina' , 'Rosie' , 300000 , 2004)
INSERT INTO MASINA (MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE) VALUES ('Volkswagen' , 'Diesel' , 'Negru' , 0 , 2016)
INSERT INTO MASINA (MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE) VALUES ('Dacia' , 'Diesel' , 'Albastra' , 2000000 , 1998)
INSERT INTO MASINA (MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE) VALUES ('Volkswagen' , 'Benzina' , 'Negru' , 0 , 2012)
INSERT INTO MASINA (MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE) VALUES ('Toyota Supra' , 'Benzina' , 'Alba' , 0 , 2018)



CREATE FUNCTION MASINI_MAI_NOI(@AN_FABRICATIE INT)
RETURNS TABLE AS RETURN SELECT * FROM MASINA WHERE AN_FABRICATIE > @AN_FABRICATIE



SELECT * FROM MASINI_MAI_NOI(2000)



CREATE FUNCTION NUMAR_MASINI_MAI_NOI (@AN_FABRICATIE INT)
RETURNS INT
BEGIN
DECLARE @NR INT = 0;
SELECT @NR = COUNT(*) FROM MASINA WHERE AN_FABRICATIE > @AN_FABRICATIE;
RETURN @NR
END;


PRINT DBO.NUMAR_MASINI_MAI_NOI(2000)



CREATE VIEW View_marca_culoare AS SELECT Model, Culoare from Masina


Select * from View_marca_culoare
where AN_FABRICATIE > 2000


Alter view View_marca_culoare AS SELECT Model, Culoare, AN_FABRICATIE from Masina



CREATE TRIGGER adaugareMasina ON MASINA FOR INSERT AS 
BEGIN
	INSERT INTO MASINA (MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE) 
	SELECT MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE 
	FROM INSERTED;
	PRINT 'Adaugat din nou!'
END

INSERT INTO MASINA (MODEL , COMBUSTIBIL , CULOARE , KM , AN_FABRICATIE) VALUES ('Tesla' , 'Electric' , 'Rosie' , 0 , 2020)

SELECT * FROM MASINA



CREATE TRIGGER deleteMasina ON MASINA FOR DELETE AS
BEGIN
	IF (EXISTS(SELECT MODEL FROM DELETED WHERE MODEL LIKE '%Toyota%'))
		RETURN
	PRINT 'Masina stearsa!'
END

DELETE FROM MASINA WHERE MODEL LIKE '%Dacia%'



CREATE TRIGGER deleteMasina ON MASINA INSTEAD OF DELETE AS
BEGIN
	IF (EXISTS(SELECT MODEL FROM DELETED))
	BEGIN
		PRINT 'Exista inregistrari!'
		DELETE FROM MASINA WHERE ID IN (SELECT ID FROM DELETED)
	END
	ELSE
		PRINT 'Nu exista!'

END

DELETE FROM MASINA WHERE MODEL LIKE '%Tesla%'

SELECT * FROM MASINA